name: for_saknon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.14.0 < 3.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/animals/
    - assets/counters/
    - assets/family/
    - assets/fruits/
    - assets/letters/
    - assets/numbers/
    - assets/vegetables/
    - assets/voices/
